version: "2"
plugins:
  nodesecurity:
    enabled: true
  tslint:
    enabled: false
    config: tslint.json
    channel: beta
  editorconfig:
    enabled: false
    channel: beta
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
